### ISSUE TITLE
[ BUG ] Select component not opening on Mobile (ref.current.open is undefined)

### ISSUE THREAD

**Issue by grkndev** [founded-labs/react-native-reusables#449]
**Reproduction link**: `<please add your repro link or Snack link here>`

**Describe the bug**  
The `@rn-primitives/select` component works fine on the web, but on iOS 18.6 it throws the following error:

```
[TypeError: ref.current.open is not a function (it is undefined)]
```

When tapping the component on mobile, `ref.current` returns an empty object, so the `open` method is missing.

**Steps to reproduce the behavior:**

1. Use `@rn-primitives/select` in a React Native / Expo project  
2. Run it on iOS Simulator (or Android Emulator)  
3. Tap on the `SelectTrigger`  
4. Observe the error in the console  

**Expected behavior**  
Tapping the `SelectTrigger` on mobile should open the `SelectContent`.

**Screenshots / Video**  
I recorded a screen capture of the issue:

https://github.com/user-attachments/assets/88168911-532d-4c94-b338-84bef747fbae

**Platform (please complete the following information):**

- Type: iOS Simulator  & Android Device
- OS: iOS 18.6  & Android 15
- Device: iPhone 16 Pro (Simulator) & Samsung S24 Ultra (Physical) 
- Framework: React Native / Expo  
- Computer: MacBook Air M4 (macOS Sequoia 15.6.1)  

**CLI output (paste the full command output)**

```bash
 LOG  {}
 ERROR  [TypeError: ref.current.open is not a function (it is undefined)]

Code: TestSelect.tsx
  38 |     if (ref.current) {
  39 |       console.log(ref.current);
> 40 |       ref.current.open();
     |          ^
  41 |     }
  42 |   }
  43 |
Call Stack
  onTouchStart (components/TestSelect.tsx:40:10)

```

**Additional context**  
Code snippet:  

```tsx
import type { TriggerRef } from "@rn-primitives/select";
import * as React from "react";
import { Platform } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectLabel,
  SelectTrigger,
  SelectValue,
} from "./ui/select";

const fruits = [
  { label: "Apple", value: "apple" },
  { label: "Banana", value: "banana" },
  { label: "Blueberry", value: "blueberry" },
  { label: "Grapes", value: "grapes" },
  { label: "Pineapple", value: "pineapple" },
];

export function SelectPreview() {
  const ref = React.useRef<TriggerRef>(null);
  const insets = useSafeAreaInsets();
  const contentInsets = {
    top: insets.top,
    bottom: Platform.select({
      ios: insets.bottom,
      android: insets.bottom + 24,
    }),
    left: 12,
    right: 12,
  };

  // Workaround for rn-primitives/select not opening on mobile
  function onTouchStart() {
    if (ref.current) {
      console.log(ref.current);
      ref.current.open();
    }
  }

  return (
    <Select>
      <SelectTrigger
        ref={ref}
        className="w-[180px]"
        onTouchStart={onTouchStart}
      >
        <SelectValue placeholder="Select a fruit" />
      </SelectTrigger>
      <SelectContent insets={contentInsets} className="w-[180px]">
        <SelectGroup>
          <SelectLabel>Fruits</SelectLabel>
          {fruits.map((fruit) => (
            <SelectItem
              key={fruit.value}
              label={fruit.label}
              value={fruit.value}
            >
              {fruit.label}
            </SelectItem>
          ))}
        </SelectGroup>
      </SelectContent>
    </Select>
  );
}
```

**Comment by Anskyuan** [comment]
Same issue
"expo": "^54.0.8",

**Comment by mrzachnugent** [comment]
Hey @grkndev , please provide a minimal reproduction repo. Here is a minimal reproduction example: https://github.com/mrzachnugent/anti-reproduction-portal-issue-expo-sdk-54-portal-1.3.0/tree/%40zach/web-mobile-select

However, I was not able to reproduce the error (see `@zach/web-mobile-select` branch).

**Comment by grkndev** [comment]
I created a new project from scratch and was able to run it without any issues. To fully understand where the problem originated, I compared the package.json files of the previous repo with the new ones I created.

As a result, I updated the versions of nativewind, expo, and reanimated to the latest versions. Currently, there doesn't seem to be any issues. 

nativewind: ^4.2.0 --> ^4.2.1
expo: ~54.0.2 --> ^54.0.8"

https://github.com/grkndev/Gomodoro/commit/22d022f9c1b398c4985df79c2869e617d5e57d00#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Example repo: https://github.com/grkndev/ExpoSDK54-Select

Screen Record: 

https://github.com/user-attachments/assets/1e8169da-40d2-47a5-aa2a-ecf7d53e5137
